endlessm/eos-knowledge-lib

data/templates/js/chunk.js
We were using the wrong variable when producing the chunk data in server-
templated news articles.
This now rightfully shows the backlink to the featured set in article pages.
https://phabricator.endlessm.com/T12631
=> Use the actual variable!

js/search/domain.js
We were passing the wrong params to fetch_update_finish which
at the very least prevented us from seeing errors in requests.
https://phabricator.endlessm.com/T13140
=> domain.js: downloader.fetch_update_finish only needs task

js/app/utils.js
Our apps own multiple dbus names, each of these names
look like:
com.endlessm.travel.en3
com.endlessm.travel.en3-1
But these names don't work with flatpak:
"By default it can only own names on the bus that
are the same as the application id, or with one
extra level of name (i.e. org.domain.app.extra)"
https://github.com/flatpak/flatpak/wiki/Metadata
Because of this we were not able to use web extensions
inside flatpak. Therefore, make sure we generate these
names with an extra level of name, i.e:
com.endlessm.travel.en.id3
com.endlessm.travel.en.id3-1
https://phabricator.endlessm.com/T12814
=> utils.js: fix web extensions dbus names

data/css/preset_a.scss
As per design review. The base css file for Cards sets
a different pixel size than that of the window. As a
consequence, we cant use ems because while set banner
uses a Card.Title, search banner uses no card, so the
base pixel sizes would be different.
https://phabricator.endlessm.com/T13202
=> Set page and search page banners should be consistent

js/app/widgets/formattableLabel.js, tests/js/app/widgets/testFormattableLabel.js
Previously we were calling Pango.parse_markup but
not actually looking at the return value to get
the parsed text.
https://phabricator.endlessm.com/T13220
=> Retrieve the return value from Pango.parse_markup

data/css/buffet.scss
Previously, while the webview on the article page was loading, you could
see a flash of the app background. Now, we add a background color to the
article page so that the transition is smoother.
https://phabricator.endlessm.com/T13169
=> Don't let background show through article page

js/app/widgets/formattableLabel.js, tests/compliance.js
This regressed on a previous commit because we were using
Pango.parse_markup() to get text to capitalize, which stripped all the
<span>s from the string.
This gets the Pango attribute list from Pango.parse_markup() and
reapplies it, as well as correcting a bug with the accel character. It
also replaces the existing test with a more robust one that looks at the
Pango.Layout directly instead of relying on formatting to be set using
Pango markup.
Original fix by @mattdangerw and @rmacqueen.
https://phabricator.endlessm.com/T13220
=> Fix search string highlighting

data/preset/encyclopedia.yaml
So that the space to the right of them
is not clickable.
https://phabricator.endlessm.com/T13198
=> Align the Card.Title modules to start

js/app/application.js, js/search/domain.js, po/POTFILES.in
This only happens when not running from a flatpak, so normally only
developers will encounter it. However, this change prevents the app from
getting stuck on the brand page, which is confusing for developers.
https://phabricator.endlessm.com/T12726
=> Quit gracefully if no manifest.json

js/search/domain.js, tests/js/search/testDomain.js
Old error message was not intuitive and did not describe the actual
fault so now we include a better one.
=> Knowledge lib: Added a small sanity check for getting the app datadir

js/search/datadir.js
On a split layout system, app data will live at a different
directory path, namely, at /var/endless-extra/
As such, we need to include this path in our list of places
to look for database content.
https://phabricator.endlessm.com/T13509
=> Include split layout path as option when looking for data dir

data/css/mesh.scss, data/css/preset_a.scss
For composite TVs, we reduce the padding under the search entry, and
reduce the minimum size of the logo to quite small.
Unfortunately we make things quite ugly at the expense of fitting
everything on the screen at 720x480.
https://phabricator.endlessm.com/T13449
=> Reduce logo size and padding on Preset A composite

data/preset/buffet.yaml, data/preset/news.yaml, js/app/modules/card/legacyPost.js
In composite TV mode, we should not let the title of the cards on the
Preset B home page take up more than one line.
https://phabricator.endlessm.com/T13527
=> Card.LegacyPost only one line in composite mode

data/css/modules/contentGroup/_contentGroup.scss, data/widgets/contentGroup/contentGroup.ui, js/app/application.js, js/app/modules/contentGroup/contentGroup.js, js/app/modules/selection/selection.js, js/app/modules/selection/xapian.js, js/search/domain.js, tests/compliance.js, tests/js/app/modules/contentGroup/testContentGroup.js, tests/minimal.js
This allows users to download an error report instead of just getting the
"Oops! There was an error" message that we previously had. Hopefully this
will allow us to diagnose failures from the field faster.
https://phabricator.endlessm.com/T12422
=> Better user-facing error state for Xapian queries

debian/eos-knowledge-0-dev.install
Since moltres got replaced by a more feature
rich command line.
https://phabricator.endlessm.com/T13538
=> Remove moltres files from debian install

js/app/modules/contentGroup/contentGroup.js
Otherwise we can get a null reference error.
=> Make sure exception is not null before retrieving stack trace

js/search/queryObject.js, tests/js/search/testQueryObject.js
Our knowledge library does use the excluded_ids and excluded_tags not
just for explicit terms but also for "further reading" articles and the
new "featured" listings so we put this functionality back into the
codebase (with exclusion of blacklisting).
Original git hash:
- ded4149754c8f437dcc7b5004d74b8413f1df397
Removal git hash:
- 514e6db37040f360636cab937e76c42c106e53e2
https://phabricator.endlessm.com/T13727
=> Knowledge lib: Return the excluded_ids and excluded_tags filtering

.gitignore, Makefile.am, configure.ac, examples/eos-player.c, lib/eosknowledgeprivate/EknMediaBin.ui, lib/eosknowledgeprivate/ekn-media-bin.c, lib/eosknowledgeprivate/ekn-media-bin.css, lib/eosknowledgeprivate/ekn-media-bin.h, lib/eosknowledgeprivate/ekn-resources.gresource.xml
EknMediaBin is a frontend widget for GStreamer playbin.
Basic features implemented:
o Audio/video playback support provided by GStreamer playbin plugin.
o GTK video sink for output (will use gtkglsink if possible and fallback to gtksink)
o UI controls implemented with regular Gtk+ widgets, themeable with CSS.
o Play/Pause, Fullscreen/Unfullscreen and volume buttons.
o Scale to control seeking and display playback position.
o Various key bindings to control playback, seeking and entering/leaving fullscreen.
(space, Right Left Up Down Page_Up Page_Down Home, f Escape)
https://phabricator.endlessm.com/T13359
=> EknMediaBin: added initial implementation of a media widget.

js/tools/kermit.js
Due to shard format changes, we store blob headers separately from the
data, so just rely on the size of the blob data.
=> kermit: use get_packed_content_size instead of get_blob_size

js/app/modules/selection/xapian.js, js/search/engine.js, js/search/moltresEngine.js, js/tools/kermit.js, tests/compliance.js
When we have a filter present, we naively request three times
the original num_desired value, to account for the filter.
This results in us sometimes getting back more results than
we originally asked for. In that case we don't want to add those
extra results to the models map.
=> Never add more than the num_desired results to content group

tools/README.md
This adds a section in the tools README documenting Autobahn.
https://phabricator.endlessm.com/T13981
=> Autobahn README

configure.ac, lib/eosknowledgeprivate/EknMediaBin.ui, lib/eosknowledgeprivate/ekn-media-bin.c
gtkglsink does not play well in the pipeline unless you
pack it inside a glsinkbin or after a glupload element.
Fixed fullscreen and show-stream-info param spec type.
Initialize video sink on realize only once.
https://phabricator.endlessm.com/T13847
=> EknMediaBin: use glsinkbin+gtkglsink as video sink

js/search/asyncTask.js, js/search/xapianBridge.js
Mainloop.idle_add always adds its callbacks with DEFAULT
priority. In the capacitate app, this has resulted
in cases where the callback is not invoked if many of
them are queued at once. Instead we should use GLib.idle_add,
which allows us to specify a higher priority.
https://phabricator.endlessm.com/T14072
=> Use GLib idle_add instead of Mainloop in async task

js/search/moltresEngine.js
Previously moltres would be able to return subsets
since it had no notion of the hierarchy between sets.
This commit enables that, by creating all the sets
once up front during init() rather than creating
them dynamically at runtime.
https://phabricator.endlessm.com/T14328
=> Make moltres work with subsets

Makefile.am
Added GIO_EXTRA_MODULES to test environment to load eknvfs.so without having to install it.
https://phabricator.endlessm.com/T14402
=> Fixed tests

js/app/historyStore.js, js/app/modules/card/list.js, js/app/readingHistoryModel.js, js/search/contentObjectModel.js, tests/js/app/modules/card/testList.js, tests/js/app/testHistoryStore.js, tests/mockReadingHistoryModel.js
Having search libraries depend on app code is incorrect and with
the impending port to C about to become impossible.
The implementation to cover the existing functionality is not very
efficient, but I doubt it will be the bottleneck in terms of
performance.
=> contentObjectModel: don't depend on reading history store

ekncontent/jasmine.json, jasmine.json
We won't run the ekncontent tests from the main directory. Those
can just be trigger by runing jasmine in the ekncontent repo.
That should make it a little easier to handle import paths and
decouple the two test suites.
=> Fix jasmine test runners

debian/eos-knowledge-0-dev.install
Our selector was two generic now that we build two libraries from
this package.
=> eos-knowledge-0-dev: don't include ekncontent pkgconfig

ekncontent/Makefile.am
This is necessary to make the build work when srcdir != builddir,
otherwise eknc-version.h can't be found during the g-ir-scanner step.
=> build: include ekncontent builddir for g-ir-scanner

Makefile.am
By setting the GJS_PATH. We shouldn't rely on make install to be
run before make check
=> Makefile: include ekncontent overrides in main testsuite

ekncontent/eknvfs/ekn-vfs.c
Some code, like file-roller, first tries to open any inputs with
g_file_new_for_uri, and then if that returns NULL, uses
g_file_new_for_path.
If we try to open a string without a scheme, we'll segfault here when we
look it up in the hash table. Just do a quick test first.
https://phabricator.endlessm.com/T14613
=> eknvfs: Fix for missing schemes

js/app/application.js, js/app/courseHistoryStore.js, js/app/historyStore.js, js/app/interfaces/card.js, js/app/interfaces/controller.js, js/app/modules/contentGroup/mediaLightbox.js, js/app/modules/layout/articleStack.js, js/app/modules/navigation/searchBox.js, js/app/modules/selection/xapian.js, js/app/widgets/eknWebview.js, js/search/domain.js, js/search/engine.js, js/search/moltresEngine.js, js/search/queryObject.js, js/search/searchProvider.js, tests/compliance.js, tests/js/app/modules/controller/testBuffet.js, tests/js/app/modules/controller/testCourse.js, tests/js/app/modules/navigation/testSearchBox.js, tests/js/app/testBuffetHistoryStore.js, tests/js/app/testCourseHistoryStore.js, tests/js/app/testMeshHistoryStore.js, tests/js/search/testEngine.js, tests/mockEngine.js, tools/kermit.js
Don't merge this till tests have been fixed!!!
Here's some API changes I'm planning to make the rest of the C port easier and generally clean up our content API a bit.
Plenty of different ways we could go about this, so putting this up quickly without looking at tests (or testing much) to get feedback.
Major changes
- Kill domain object v2
- Application calls downloader directly (needed to port domain to C but leave downloader in js for the time being)
- Remove broken command line option setting datadir
- Some general cleanups
Probably a bit easier to go commit by commit. The diff on domain is kinda terrible, but its basically just moving things around.
=> T13418 kill domain v2

ekncontent/Makefile.am, ekncontent/docs/reference/ekncontent/eos-knowledge-content-docs.xml, ekncontent/docs/reference/ekncontent/eos-knowledge-content-sections.txt, ekncontent/ekncontent/eknc-query-results.c, ekncontent/ekncontent/eknc-query-results.h, ekncontent/ekncontent/eos-knowledge-content.h, ekncontent/overrides/EosKnowledgeContent.js, ekncontent/tests/ekncontent/testQueryResults.js
This object is a replacement for the property bag that's returned in the
JS version of Engine.get_objects_for_query(). It is immutable and also
does not expose any constructor API other than g_object_new.
=> ekncontent: Add EkncQueryResults object

js/app/modules/contentGroup/mediaLightbox.js
Currently, if the lightbox widget is a video, it will
keep playing in the background after the lightbox has
closed. So we need to destroy the widget when lightbox
closes or when we switch to another piece of content.
https://phabricator.endlessm.com/T14931
=> Destroy lightbox widget when closing lightbox

js/app/modules/contentGroup/contentGroup.js, po/POTFILES.in
contentGroup.js needs to go in POTFILES.in, and the string should be in
double quotes because otherwise xgettext gets confused.
https://phabricator.endlessm.com/T14969
=> Fix i18n of "See more" label

ekncontent/ekncontent/eknc-xapian-bridge.c, js/app/interfaces/card.js, js/app/interfaces/controller.js
Previously we were implicitly relying on integer
overflow to convert -1 to a large int. This is dangerous
and was partly responsible for a serious bug we found on
ARM. Instead we should explicitly set the integer
to be the max int.
https://phabricator.endlessm.com/T15009
=> Don't rely on integer overflow!

js/app/application.js
If both a css/scss file and a theme are specified via the command
line, let the manual theme override the theme.
https://phabricator.endlessm.com/T15008
=> application: css file supersedes theme

lib/eosknowledgeprivate/ekn-media-bin.c
Using GST_SEEK_FLAG_TRICKMODE flag while performing a seek makes
gst performance to drop considerably.
https://phabricator.endlessm.com/T15110
=> EknMediaBin: do not use GST_SEEK_FLAG_TRICKMODE flag

data/css/library_list.scss
It had none before and had a background that did not match
the rest of the app's theme.
https://phabricator.endlessm.com/T15132
=> Add styling to search results page in library list template

debian/control
The content library now serves up shards as part of its public
api, so we should add this dependency
https://phabricator.endlessm.com/T15211
=> control: content dev package depends on shard dev package

ekncontent/ekncontent/eknc-domain.c
There's a few places where we had code which looked like
if (!g_file_exists)
create_the_file;
We can run into problems here if two domains are racing to setup
directories and symlinks for the same subscriptions at the same
time. In that case you might make it through the existence check,
but by the time you get to actual file creation another domain
in another process has already completed the check.
I believe this is happening with multi-threaded make in our test
runner on ci at the moment, and could also happen when spinning up
the global search provider at the same time as an application.
Instead we move to
create_the_file;
if (!error matches G_IO_ERROR_EXISTS)
error out;
This way if another domain has one the file creation race, we can
still proceed as normal. …
=> eknc-domain: make robust to parallel initialization

ekncontent/Makefile.am
If we are setting XDG_DATA_DIRS we need to make sure we provide
some defaults in case the variable is empty, as described here
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
https://phabricator.endlessm.com/T14909
=> Makefile: properly set XDG_DATA_DIRS in the test environment

data/preset/A.yaml
I think we never noticed this before because we used
to always have app banner images which were wider
than the search bar.
https://phabricator.endlessm.com/T15530
=> Horizontally center the app banner

tools/introspect.js
The "introspect" tool previously supported module names as its argument
(e.g. "Filter.Unread"). This adds a --file argument that takes a path
which will be imported instead.
https://phabricator.endlessm.com/T15141
=> introspect: Support absolute file paths

js/app/interfaces/arrangement.js
We already add it once in the create_card function.
No need to do it again in set_models.
https://phabricator.endlessm.com/T13398
=> Don't add card to arrangement map twice.

lib/eosknowledgeprivate/ekn-media-bin.css
On ARM the video widget uses alpha for performance reasons which makes
video padding bars transparent instead of black.
https://phabricator.endlessm.com/T16107
=> EknMediaBin: set background color to black.

eos-knowledge-lib.modules
Remove compass and dbusmock, as they are no longer needed. Replace the
check for the SCSS compiler with the compiler binary name from libsass.
https://phabricator.endlessm.com/T16140
=> Update JHBuild dependencies

js/app/modules/layout/articleStack.js
To avoid leaking an article content widget (WebkitWebView) each time
we switch to a new one we explicitly destroy the child with child.destroy()
instead of removing it from the hierarchy and relaying on GC. (Which never
happens because we are probably holding a reference in JS)
https://phabricator.endlessm.com/T15913
=> Layout.ArticleStack: explicitly destroy children.

eos-knowledge-lib.modules
eos-sdk does not depend on WebKit or NaturalDocs any longer.
https://phabricator.endlessm.com/T16203
=> jhbuild: Remove webhelper deps from eos-sdk deps

debian/control
It writes an arch-dependent library path into its scripts, so it can't be
arch-independent.
https://phabricator.endlessm.com/T14833
=> control: Make eos-knowledge-0-bin arch-dependent

js/app/modules/layout/dynamicBackground.js
Previously the dynamic background would have overridden the CSS
overrides.
https://phabricator.endlessm.com/T16822
=> Layout.DynamicBackground: Allow CSS overrides

Makefile.am, configure.ac, docs/Makefile.am
Something changed in eos-knowledge-lib so that introspecting now requires imports.gi.EosKnowledgeContent. We didn't make that available to the introspect-local utility, so it broke the build.
https://phabricator.endlessm.com/T16717
=> Fix documentation build

Makefile.am
The "|| rm -f $@" was causing the make recipe to succeed even if the
SCSS compilation failed. I don't think we needed the rm command anyway,
so just remove it.
https://phabricator.endlessm.com/T16939
=> build: Fail when SCSS compilation fails

js/app/application.js
Only do so when it has been exported previously.
=> application: don't unexport KnowledgeSearchIface unconditionally

data/preset/A.yaml, data/preset/B.yaml, data/preset/buffet.yaml
These presets will use Banner.Dynamic instead of Banner.App going
forward, in order to keep them easily internationalizable.
https://phabricator.endlessm.com/T16725
=> presets: Switch to Banner.Dynamic in A, B, Buffet

data/css/blog.scss
Refactored some of blog template to reflect default theme changes.
- Deleted unnecessary CSS that is repetitive of default theme CSS:
- Pager.Simple bg-color
- Layout.Sidebar .CardTitle hover bg-color:transparent
- Card.DefaultFamily hover-color, width-f title/synopsis/context font-size
- Rearranged some CSS to work properly
- Layout.Sidebar CardTitle padding needs to go inside .CardTitle__title; hover styling
also needs to apply to :active styling; highlighted bg-color needs to go inside
.CardTitle__title
- set-page & search-page Banner.Set & Banner.Search styling needs to go inside
Layout.Sidebar .content styling. (I don't think this is great; it probably
needs to be fixed in a later update of the default theme; it's too specific.)
- New/forgotten styling additions
- no-results-message …
=> Blog template refactor for default theme changes

data/css/buffet.scss, data/css/modules/card/_deck.scss, data/css/news.scss
Fixing 3 quick things that were overlooked in the default theme PR:
- In Buffet template, `Layout.SideMenu` had incorrect highlighted/active state background-color
- In News template, `Layout.TopMenu` (`Arrangement.SideBySide`) had incorrect highlighted/active state background-color
- `Card.Deck` had no hover state
=> Bugfixes from default theme: Buffet/News highlighted state, Card.Deck hover state

ekncontent/ekncontent/eknc-engine.c
The comment I added in fce3237a23dade71bc6b27612a635e317e6e4b06 was
in the wrong function - move it to the correct one.
=> Move comment to correct place

ekn-app-runner.in, tools/eminem.in, tools/introspect.in, tools/kermit.in, tools/picard.in
Don't explicitly set DEBUG_COMMAND to an empty value in the wrapper
scripts, to allow specifying tools other than gdb, e.g.
DEBUG_COMMAND=valgrind
=> Allow DEBUG_COMMAND to be specified directly

ekncontent/ekncontent/eknc-domain.c
This function doesn't "fix" the passed query object.
=> Correct doc comment for eknc_domain_query

data/css/modules/arrangement/_sideBySide.scss, data/css/modules/layout/_topMenu.scss, data/css/news.scss, data/preset/news.yaml, js/app/modules/arrangement/sideBySide.js
Some extra CSS removal from the News template that is not necessary on the template level.
- Deleted CSS having to do with text-transform, color, and some margin on content groups that
should inherit from other content group styling
- Moved .ContentGroup--outercontainer upward in code for readability
- Combined CSS for .ContentGroup--complementarycontent and .LayoutResponsiveMargins--complementarycontent
- Changed trigger text to "More news from ...."
And, some default theme design QA on the Layout.TopMenu and its new dropdown menu for news template
https://phabricator.endlessm.com/T17424
=> Refactoring some News CSS & YAML

ekncontent/docs/reference/ekncontent/Makefile.am
Gtk-doc needs to have base file names in IGNORE_HFILES, not full paths.
(Once again, I'm not sure how this worked before! Maybe we upgraded
gtk-doc on the autobuilder?)
https://phabricator.endlessm.com/T17601
=> build: Ignore eknc-enums.h correctly

ekncontent/ekncontent/eknc-domain.c
In on_xapian_test_response(), the query object is freed when the GTask's
data is replaced in send_query_to_xapian_bridge(), so take a reference
before calling that function.
https://phabricator.endlessm.com/T17779
=> ekncontent: Fix use-after-free

tools/picard.js
Avoid passing extra arguments to GI functions.
https://phabricator.endlessm.com/T17220
=> picard: Eliminate 'too many arguments' warnings

js/app/application.js
Domain.get_subscription_entries no longer exists, we
forgot to update this call to the new ekncontent API.
https://phabricator.endlessm.com/T18050
=> application: Fix content download dialog

ekncontent/ekncontent/eknc-domain.c
This commit fixes a couple of calls to
eknc_domain_process_subscription() so they return on error rather than
reusing the already set GError pointer (which leads to an assertion
failure).
It also fixes the error handling of eknc_domain_get_impl() so that it
returns NULL if the initialization failed.
=> ekncontent: Don't ignore error conditions

js/app/modules/arrangement/constrained.js
Emeus.ConstraintLayout.add_constraint can not be used as a forEach()
callback because it only expect one argument
https://phabricator.endlessm.com/T18829
=> constrained: fix forEach() callback warning

data/css/gallery.scss, data/preset/gallery.yaml
Gallery template:
- vertically center the logo (Banner.Dynamic) inside the top menu
- Add padding to the sides of the search-page Layout so that the cards don't have so much space between them on a 1080p display
https://phabricator.endlessm.com/T18872
=> T18872 - Gallery Template: logo vertical center, search page side padding

tests/autobahn/test-autobahn-catalog
I thought the regex '^# ?$' would cover both cases of the output for
polib < 1.0.7 and >= 1.0.7. However, it doesn't. For simplicity, just
ignore all trailing spaces.
https://phabricator.endlessm.com/T18981
=> tests: Ignore trailing space in polib output

ekncontent/docs/reference/ekncontent/eos-knowledge-content-docs.xml, ekncontent/docs/reference/ekncontent/eos-knowledge-content-sections.txt, ekncontent/ekncontent/eknc-article-object-model.c, ekncontent/ekncontent/eknc-article-object-model.h, ekncontent/overrides/EosKnowledgeContent.js, ekncontent/tests/ekncontent/testArticleObjectModel.js
This property is the dates referred to in the content, which we'll
use for things like WikiArt to add a date to the end of it.
https://phabricator.endlessm.com/T17886
=> ekncontent: Add temporal-coverage property to ArticleObjectModel

js/app/modules/layout/articleStack.js
Apparently if the video player is running it will starve out the main
loop so that the load_content_promise() in the next line will resolve
only after a few seconds. I'm not sure why this happens, but we can work
around it by stopping the video before loading a new one.
https://phabricator.endlessm.com/T19384
=> Layout.ArticleStack: Stop video before switching

ekn-app-runner.in
For some reason, this makes debugging tools stop working inside Flatpak.
Probably something to do with tracing child processes.
https://phabricator.endlessm.com/T19535
=> ekn-app-runner: Remove 'exec'

js/app/modules/contentGroup/contentGroup.js
This replaces the GtkSpinner in ContentGroup.ContentGroup with an icon
that's not animated. The animation is somehow interacting with the video
player's gtkglsink component and spamming the main loop with expose
events.
https://phabricator.endlessm.com/T19464
=> ContentGroup.ContentGroup: Replace spinner

js/app/historyStore.js, js/app/utils.js, js/app/widgets/webShareDialog.js, tests/js/app/testHistoryStore.js, tests/js/app/testUtils.js
Use WebShareDialog::transaction-done to determine if sharing was canceled
or not to properly report to the metrics system.
https://phabricator.endlessm.com/T18524
=> HistoryStore: determine if Facebook sharing was canceled.

js/app/widgets/webShareDialog.js, tests/js/app/testHistoryStore.js
This is in order to prevent the tests from trying to access the real
org.gnome.OnlineAccounts object, which (1) doesn't exist in the CI
environment and (2) could do unwanted actions on a real system.
https://phabricator.endlessm.com/T19798
=> webShareDialog: Allow dependency-injecting the DBus manager

ekncontent/ekncontent/eknc-database-manager.c
I was freeing up disk space and found this unpushed patch in my EKL tree - `priv` isn't actually used in either case.
I seem to not have all the currently required ekl dependencies installed, so haven't tested this change as updated to current master, but it seems obvious and useful to push.
=> Remove unused eknc_database_manager_get_instance_private() calls

ekncontent/ekncontent/eknc-article-object-model.c, ekncontent/ekncontent/eknc-article-object-model.h, ekncontent/ekncontent/eknc-content-object-model.c, ekncontent/ekncontent/eknc-content-object-model.h, ekncontent/ekncontent/eknc-query-object.c, ekncontent/ekncontent/eknc-query-object.h, ekncontent/ekncontent/eknc-query-results.c, ekncontent/ekncontent/eknc-set-object-model.c, ekncontent/ekncontent/eknc-set-object-model.h, ekncontent/ekncontent/eknc-utils.c, ekncontent/overrides/EosKnowledgeContent.js, ekncontent/tests/ekncontent/testQueryObject.js, js/app/application.js, js/app/courseHistoryStore.js, js/app/interfaces/card.js, js/app/modules/navigation/searchBox.js, js/app/modules/selection/all.js, js/app/modules/selection/allSets.js, js/app/modules/selection/articleContext.js, js/app/modules/selection/contentForSet.js, js/app/modules/selection/featuredFirst.js, js/app/modules/selection/next.js, js/app/modules/selection/related.js, js/app/modules/selection/search.js, js/app/modules/selection/setCrossSection.js, js/app/modules/selection/suggested.js, js/app/modules/selection/supplementary.js, tests/js/app/modules/selection/testXapian.js, tools/kermit.js
Replaces most of the GVariant properties with `G_TYPE_STRV` boxed properties.
https://phabricator.endlessm.com/T19625
=> Replace all "as" GVariant properties

ekncontent/docs/reference/ekncontent/eos-knowledge-content-sections.txt, ekncontent/ekncontent/eknc-content-object-model.c, ekncontent/ekncontent/eknc-content-object-model.h, ekncontent/ekncontent/eknc-utils.c, ekncontent/overrides/EosKnowledgeContent.js, ekncontent/tests/ekncontent/testContentObjectModel.js
Instead of string-to-JSON-to-GVariant, we now go string-to-JSON. We can
now drop another problematic JSON-to-GVariant conversion.
https://phabricator.endlessm.com/T20702
=> ekncontent: Change discovery-feed-content property to JsonObject*

ekncontent/ekncontent/eknc-media-object-model.c, ekncontent/tests/ekncontent/testMediaObjectModel.js
This is the EKN URI for the article which embeds this Media Object,
if it has an embedder and the embedder is known (otherwise it is
an empty string).
https://phabricator.endlessm.com/T21114
=> ekncontent: Add "parent-uri" prop to EkncMediaObjectModel

docs/framework/tutorial/ingester-full-code.md
For some reason the index.js is not highlighted by default, unlike the
two json files in this same page which are properly highlighted.
=> docs, ingester tutorial: Highlight code

data/widgets/view/document.ui, data/widgets/websharedialog.ui, eos-knowledge.gresource.xml, js/app/modules/contentGroup/contentGroup.js, js/app/modules/view/document.js, js/app/widgets/spinnerReplacement.js, js/app/widgets/webShareDialog.js
GtkSpinner animations still don't interact well with the video player.
It is causing async operations not to resolve. Replace existing
GtkSpinners with the EknSpinnerReplacement that we already used in
ContentGroup.
https://phabricator.endlessm.com/T21362
=> Remove all remaining GtkSpinners

js/app/widgets/themeableImage.js
On close pixbuf loaders try to finish parsing the image and can throw
exceptions if there is any error. But since we are not trying to
actually load the image, we just wanted to ge the image size,
we need to ignore them.
https://phabricator.endlessm.com/T21534
=> ThemeableImage: ignore PixbufLoader exceptions

js/app/widgets/themeableImage.js
Fix pixbuf loader loop.
g_input_stream_read_bytes() started to return a zero-length GBytes
instead of null when there is no more data causing an infinite loop.
https://phabricator.endlessm.com/T21788
=> ThemeableImage: fix infinite loop bug

ekncontent/Makefile.am, ekncontent/configure.ac, ekncontent/tests/ekncontent/testQueryObject.js
We're switching to a new version of Xapian, which means we're going to
be using a new version of the Xapian-GLib bindings.
https://phabricator.endlessm.com/T21284
=> Depend on xapian-glib-2.0

docs/framework/tutorial/install.md
Error gives:
```tar (child): --strip-components=1: Cannot open: No such file or directory```
=> Fix tutorial node tar extraction step

data/css/thematic.scss
It's not clear why this margin was there, since there was already other
padding separating the search box from the edge of the window. It only
served to create an odd gap between the width of the search box and the
width of the popup.
https://phabricator.endlessm.com/T20352
=> thematic: Remove search box right margin

tests/compliance.js
We need to register resource before importing HistoryStore because it imports
WebShareDialog which needs a resource for its template.
https://phabricator.endlessm.com/T22178
=> tests/compliance.js: register resource before importing HistoryStore

tools/eminem.js
We are dropping support for this file since a particular SDK should only
work with one particular on-disk database format.
https://phabricator.endlessm.com/T22395
=> eminem: Ignore EKN_VERSION

Makefile.am
Test fail under xvfb because libGLX is not properly initialized by
the linker and for some unknown reason pre loading libGL makes
GLX to work.
https://phabricator.endlessm.com/T21657
=> Workaround for CI test failure

js/app/modules/contentGroup/mediaLightbox.js
When the lightbox is exited, or any other navigational change occurs, we
should stop any media file playing in the lightbox.
https://phabricator.endlessm.com/T20433
=> ContentGroup.MediaLightbox: Drop submodule on nav change

data/css/modules/navigation/_searchBox.scss, js/app/modules/navigation/searchBox.js, js/app/modules/window/simple.js, js/app/widgets/searchBox.js, po/POTFILES.in
This removes the default GtkEntry autocomplete popup in favour of a more
customizable GtkPopover, since a lot of the requested visuals weren't
possible with the default popup (including rounded corners.)
Separates the theming of the popup coming from a search box in the title
bar, from the popup coming from the main search box. Adds mixins to the
SCSS with the various size parameters to ease tweaking in the future.
In some cases (focus out, click) the popup doesn't have the "popdown"
animation. This is because when the window starts animating, the popup's
animation is slotted in after the window's animation, which makes it
jump to the side of the window as its search box starts animating away.
https://phabricator.endlessm.com/T22184
=> Navigation.SearchBox: Rewrite popup and retheme

js/app/widgets/eknWebview.js
We want to allow users to copy images from
webkit to other applications. So we should not
exclude the Copy Image menu item from Webkit's
context menu.
[endlessm/eos-sdk#3814]
=> Allow the Copy Image menu item to be included in Webkit Context Menu

js/framework/application.js, js/framework/knowledge.js, js/framework/modules/selection/contentForSet.js, js/framework/utils.js, tests/compliance.js, tests/js/framework/modules/layout/testArticleStack.js, tests/mockFactory.js
This is the result of scanning all the sources in js/ and tests/ with
moz60tool (https://gitlab.gnome.org/ptomato/moz60tool) and fixing the
issues.
Especially the str.replace('foo', 'bar', 'g') which was actually already
invalid since GNOME 3.26, was actually causing some minor bugs.
=> Fix source code that's incompatible with mozjs60

js/framework/application.js, js/framework/courseHistoryStore.js, js/framework/historyStore.js, js/framework/interfaces/card.js, js/framework/modules/contentGroup/mediaLightbox.js, js/framework/modules/layout/articleStack.js, js/framework/modules/navigation/searchBox.js, js/framework/modules/selection/xapian.js, js/framework/moltresEngine.js, js/framework/promiseWrapper.js, js/framework/widgets/eknWebview.js, tests/compliance.js, tests/js/framework/modules/controller/testCourse.js, tests/js/framework/modules/controller/testMesh.js, tests/js/framework/modules/navigation/testSearchBox.js, tests/js/framework/modules/selection/testNext.js, tests/js/framework/modules/selection/testXapian.js, tests/js/framework/testCourseHistoryStore.js, tests/js/framework/testMeshHistoryStore.js, tests/mockEngine.js
The promisify function in upstream GJS (available from GNOME 3.30
onward) has more features, such as better stack traces, the ability to
work on local Gio.File instances, and conforms better to the original
callback-based API.
Once eos-knowledge-lib switches to the GNOME 3.30 runtime, the
_promisify and _LocalFilePrototype code can be removed, since it will be
built in to GJS.
=> Include better promisify function from upstream GJS

js/framework/application.js, js/framework/promiseWrapper.js, js/framework/utils.js
~~This pull request is stacked on top of #1683 and #1684, so review those first.~~
To test: it can be a bit difficult, since it's not possible to pass file descriptors with any of the usual DBus tools like D-Feet or `gdbus call`. Also GJS does not support passing file descriptors either out of the box (https://gitlab.gnome.org/GNOME/gjs/issues/204). I think maybe the best way to test it is to checkout endlessm/hack-toolbox-app branch `controlpanel` and build and run it:
```sh
./build-flatpak.sh
flatpak remote-add --no-gpg-verify hack-toolbox-local repo
flatpak install --assumeyes repo com.endlessm.HackToolbox
flapjack run com.endlessm.dinosaurs.en  # run with flapjack, assuming you have built this branch
flatpak run com.endlessm.HackToolbox & sleep 1 ; gjs tools/trigger.js …
```
=> Restart API

js/framework/utils.js, lib/eosknowledgeprivate/EknMediaBin.ui, lib/eosknowledgeprivate/ekn-media-bin.c
This branch fixes several small problems with the MediaBin widget which may have contributed to instability we observed after playing videos.
https://phabricator.endlessm.com/T26126
=> Check that GdkWindow exists before using it

js/framework/interfaces/filter.js, js/framework/interfaces/module.js, js/framework/interfaces/order.js, tests/js/framework/interfaces/testModule.js, tests/js/framework/testKnowledge.js
This is a workaround for an issue where gjs on aarch64 crashes creating
a GObject interface without GTypeName:
<https://gitlab.gnome.org/GNOME/gjs/issues/307>
=> Consistently set GTypeName for GObject interfaces

js/framework/widgets/PDFView.js
Instead of gdk_screen_get_width, we should use gdk_monitor_get_geometry.
https://phabricator.endlessm.com/T28284
=> Replace deprecated GdkScreen get_width in PDFView

js/framework/application.js, js/framework/articleHTMLRenderer.js, tools/picard.js
Now that we have removed a lot of custom CSS from the chrome around knowledge applications, I think it is reasonable to always use the system icon theme. As far as I can tell, there are no special EndlessOS-specific icons being used here, and I haven't noticed any problems with icons using the Adwaita theme. On Endless OS, applications will continue to use the system icon theme so this change won't have any effect.
https://phabricator.endlessm.com/T30537
=> Remove hard-coded icon theme setting

releases/sdk6.md
I skipped the mentions on EGL-GLES improvements as Dylan suggested (not that I agree though, the fixes are there after all, right?)
https://phabricator.endlessm.com/T30539
=> Add release notes for SDK version 6.0

js/framework/modules/layout/articleStack.js
When loading OpenZIM articles, the tooltips for internal links were
its URIs and not the title.
=> Fix tooltips when loading OpenZIM articles

js/framework/modules/view/document.js
This allow same page anchor links (e.g. ending with #the-section) to
work even if the section is not declared in the article table of
content.
This is particularly useful for Wikipedia OpenZIM articles that
preserves references links and the references section of articles.
=> Allow navigate to same page anchor links for non declared sections
