endlessm/eos-knowledge-lib

data/css/modules/card/_legacyPolaroid.scss
data/css/preset_a.scss

Since apps with these cards were made before the notion
of highlights existed.
https://phabricator.endlessm.com/T13201

Legacy polaroid should not change color when highlighted

---

js/app/modules/selection/articlesForSetCrossSection.js

https://phabricator.endlessm.com/T12846

T12846 (quick fix)

---

js/app/articleHTMLRenderer.js
js/app/modules/layout/articleStack.js
js/app/widgets/eknWebview.js
tests/js/app/testArticleHTMLRenderer.js

Based on Martin workaround
https://phabricator.endlessm.com/T12960

Use custom uri scheme for license links

---

js/app/widgets/formattableLabel.js
tests/js/app/widgets/testFormattableLabel.js

https://phabricator.endlessm.com/T13271

T13271 (fixup)

---

js/app/modules/selection/articleContext.js

https://phabricator.endlessm.com/T13274

T13274 (fix)

---

data/widgets/tooltips.ui

https://phabricator.endlessm.com/T13273-part2

data/widgets/tooltips.ui: updated license tooltip message.

---

Makefile.am
eos-knowledge.gresource.xml
js/app/modules/layout/overlay.js
tests/js/app/modules/layout/testOverlay.js

Introduces a Layout module that works pretty much like Gtk.Overlay.
https://phabricator.endlessm.com/T12440

Layout.Overlay

---

.gitignore
Makefile.am
js/app/widgets/eknWebview.js
lib/eosknowledgeprivate/EknRuntimeDocumentViewer.ui
lib/eosknowledgeprivate/ekn-resources.gresource.xml
lib/eosknowledgeprivate/ekn-runtime-document-viewer.c
lib/eosknowledgeprivate/ekn-runtime-document-viewer.h

This widget is mainly intended to display file:// uris
https://phabricator.endlessm.com/T13273

lib/eosknowledgeprivate: Added new EknWebViewDialog widget. 

---

data/css/modules/card/_list.scss
js/app/interfaces/card.js

To match designs. Previously, the synopsis
text was too large relative to the title
text.
https://phabricator.endlessm.com/T13216

Adjust Card.List font sizes

---

js/app/modules/layout/articleStack.js

Do not depend on gtk animations to cleanup old documents.
https://phabricator.endlessm.com/T13462

Layout.ArticleStack: fixed document_card leak.

---

data/css/modules/banner/_set.scss
data/css/modules/card/_thumb.scss
data/css/modules/navigation/_searchBox.scss
js/app/interfaces/card.js
tests/compliance.js
tests/js/app/modules/card/testDeck.js
tests/js/app/modules/card/testLegacyPolaroid.js
tests/js/app/modules/card/testLegacyPost.js
tests/js/app/modules/card/testList.js
tests/js/app/modules/card/testPost.js
tests/js/app/modules/card/testSequence.js
tests/js/app/modules/card/testText.js
tests/js/app/modules/card/testThumb.js
tests/js/app/modules/card/testTitle.js

https://phabricator.endlessm.com/T13467

Various fixes

---

README.md
configure.ac
eos-knowledge-lib.modules
js/app/config.js.in.in
js/app/utils.js

A better README, a JHbuild moduleset to make it easy to get started, and also we make a dependency optional.
https://phabricator.endlessm.com/T13015

Information for contributors!

---

autogen.sh

Jasmine was the only module before and has been removed so this is dead
code that needed removing.
https://phabricator.endlessm.com/T13692

Knowledge Lib: Remove code to handle git submodules

---

js/tools/kermit.js

`kermit stat <shard_path>` will do some (potentially slow) calculations
on a shard's use of disk space. Specifically, it calculates the amount
of wasted space in between blocks, and also calculates maximums and
means of blobs by content type.
https://phabricator.endlessm.com/T13672

kermit: add stat function

---

data/css/encyclopedia.scss

It's easy to forget that & repeats all outer selectors too.
https://phabricator.endlessm.com/T11455

Fix &-selector misuse

---

Makefile.am
eos-knowledge.gresource.xml
js/app/modules/arrangement/accordion.js
tests/js/app/modules/arrangement/testAccordion.js

This is an arrangement that shows cards in
a vertical arrangement layout. Each card
is placed into an expander, which will expand
when the title is clicked.
https://phabricator.endlessm.com/T13573

Add accordion arrangement

---

js/tools/kermit.js

Reverts endlessm/eos-knowledge-lib#1205

Revert "kermit: add stat function"

---

tools/README.md
tools/ka-customizer
tools/ka-customizer-installer
tools/ka-customizer-runner

Little gui for playing with the new CLI options
https://phabricator.endlessm.com/T13878

ka-customizer

---

lib/eosknowledgeprivate/EknMediaBin.ui
lib/eosknowledgeprivate/ekn-media-bin-fullscreen.svg
lib/eosknowledgeprivate/ekn-media-bin-pause.svg
lib/eosknowledgeprivate/ekn-media-bin-play.svg
lib/eosknowledgeprivate/ekn-media-bin-restore.svg
lib/eosknowledgeprivate/ekn-media-bin-volume-high.svg
lib/eosknowledgeprivate/ekn-media-bin-volume-low.svg
lib/eosknowledgeprivate/ekn-media-bin-volume-medium.svg
lib/eosknowledgeprivate/ekn-media-bin-volume-muted.svg
lib/eosknowledgeprivate/ekn-media-bin.c
lib/eosknowledgeprivate/ekn-media-bin.css
lib/eosknowledgeprivate/ekn-resources.gresource.xml

Implemented eos design using CSS and added named icons for playback actions
https://phabricator.endlessm.com/T13360

EknMediaBin: implemeted EOS design.

---

Makefile.am

https://phabricator.endlessm.com/T13360

EknMediaBin: added icons to EXTRA_DIST

---

js/app/modules/selection/allHighlights.js
js/app/modules/selection/xapian.js

https://phabricator.endlessm.com/T10252

Knowledge lib: RFC Get allHighlights to show featured articles first

---

tools/README.md

https://phabricator.endlessm.com/T13981

Add documentation for picard

---

eos-knowledge-lib.modules

https://phabricator.endlessm.com/T14015

Add emeus to the jhbuild moduleset

---

tools/README.md

https://phabricator.endlessm.com/T13789

tools: Basic documentation for kermit and eminem

---

data/css/buffet.scss
data/css/modules/card/_list.scss
data/css/news.scss
data/widgets/card/list.ui
js/app/modules/card/list.js

Previously we were doing all sorts of craziness
in the size allocate routine. This cleans that
up and adds a width_for_height method too.
https://phabricator.endlessm.com/T13216

Rewrite list card to not be so jittery

---

js/app/modules/card/thumb.js

T13535 (quick fix for thumb card)

---

js/search/mediaObjectModel.js
tests/js/search/testMediaObjectModels.js

We add a "poster" attribute to the VideoObjectModel to marshall poster images
to display when the video is about to play.
https://phabricator.endlessm.com/T14156

Add poster attribute to VideoObjectModel

---

js/search/engine.js

https://phabricator.endlessm.com/T14073

Engine: init EknVfs shards in default_app_id setter.

---

lib/eosknowledgeprivate/ekn-media-bin.c

https://phabricator.endlessm.com/T14196

EknMediaBin: handle end of stream message.

---

Makefile.am
tests/js/app/modules/controller/testCourse.js
tests/js/app/modules/navigation/testSearchBox.js
tests/js/app/testCourseHistoryStore.js
tests/js/app/testHistoryStore.js
tests/js/app/testMeshHistoryStore.js

Fix tests for capacitate app

---

Makefile.am
data/css/_base.scss
data/css/widgets/_eknMediaBin.scss
examples/eos-player.c
lib/eosknowledgeprivate/ekn-media-bin.c
lib/eosknowledgeprivate/ekn-media-bin.css

https://phabricator.endlessm.com/T13360

EknMediaBin: updated style to latest specs.

---

js/search/domain.js
js/search/engine.js
lib/eknvfs/ekn-file-input-stream-wrapper.c
lib/eknvfs/ekn-file.c
lib/eknvfs/ekn-vfs.c
lib/eosknowledgeprivate/ekn-util.c
lib/eosknowledgeprivate/ekn-util.h
tests/js/search/testDomain.js

Added domain property to use as the default domain for ekn uri searches.
Added append-shards action signal to add a list of shards for a particular domain.
Removed obsolete shards property
https://phabricator.endlessm.com/T14073

EknVfs: added support for multiples domains

---

tools/ka-customizer
tools/ka-customizer-runner

https://phabricator.endlessm.com/T14250

ka-customize-runner: keep args quoted

---

Makefile.am
data/preset/library-list.yaml
js/app/modules/pager/simple.js
js/app/modules/selection/subsetsForSet.js

The new FNDE apps need a separate subset page,
in addition to the set page, so let's add
one to the Pager.
https://phabricator.endlessm.com/T13926

Add subset page to Pager.Simple

---

data/preset/library-list.yaml

https://phabricator.endlessm.com/T13926

Fixes for library-list template

---

ekncontent/eknvfs/ekn-vfs.c

Handle NULL from vfs->get_supported_uri_schemes()
Use local vfs instance instead of using g_vfs_get_local()
https://phabricator.endlessm.com/T14455

EknVfs: fixed crash when running inside flatpak

---

ekncontent/eknvfs/ekn-vfs.c
tests/mockEngine.js

Add reference to priv->local object.
Use g_initable_new() for initiable types.
https://phabricator.endlessm.com/T14455

EknVfs: fixed segfault while initializing instance

---

data/css/course.scss

Style fixups based on design review with Robin

---

README.md
eos-knowledge-lib.modules

https://phabricator.endlessm.com/T14468

JHbuild fixes

---

configure.ac
tests/js/app/interfaces/testCard.js

https://phabricator.endlessm.com/T14477

Fix deadlocked builds

---

Makefile.am

"depedencies" --> "dependencies"

Fix typo in Makefile

---

Makefile.am
data/css/course.scss
data/css/escola.scss
data/css/modules/window/_simple.scss
data/preset/course.yaml
data/preset/escola.yaml
data/widgets/banner/dynamic.ui
js/app/modules/banner/dynamic.js

https://phabricator.endlessm.com/T14133

Add yaml and css for escola template

---

data/css/course.scss
data/css/escola.scss
data/preset/escola.yaml
data/widgets/card/list.ui
js/app/interfaces/card.js
js/app/modules/card/list.js
tests/js/app/interfaces/testCard.js

Based on Design QA
https://phabricator.endlessm.com/T14133

Style fixes for escola template

---

ekncontent/eknvfs/ekn-vfs.c

https://phabricator.endlessm.com/T14455

EknVfs: improved crasher fix.

---

configure.ac
js/app/modules/contentGroup/mediaLightbox.js
lib/eosknowledgeprivate/ekn-media-bin.c

With playbin3 we always get eos event, even if we initially set the state to paused
which is needed to show the first frame of the video and make the widget request
the video size.
https://phabricator.endlessm.com/T14316

EknMediaBin: ported to playbin3

---

lib/eosknowledgeprivate/ekn-media-bin.c

GtkGstGLWidget does not support reparenting to a different toplevel
because the gl context is different and the pipeline does not know it
changes, so as a temporal workaround we simply reconstruct the whole
pipeline.
https://bugzilla.gnome.org/show_bug.cgi?id=775045
https://phabricator.endlessm.com/T14099

EknMediaBin: workaround fullscreen bug

---

examples/eos-player.c
lib/eosknowledgeprivate/EknMediaBin.ui
lib/eosknowledgeprivate/ekn-media-bin.c
lib/eosknowledgeprivate/ekn-media-bin.css
lib/eosknowledgeprivate/ekn-media-bin.h

Added audio-mode property
https://phabricator.endlessm.com/T14204

EknMediaBin: implemented basic audio mode.

---

configure.ac
js/app/widgets/PDFView.js

https://phabricator.endlessm.com/T14205

KnowledgeDocument: use EknMediaBin to playback audio links

---

eos-knowledge-lib.modules

https://phabricator.endlessm.com/T14821

Moduleset fixes

---

debian/gir1.2-eosknowledgecontent-0.install

https://phabricator.endlessm.com/T14832

Actually install eosknowledgecontent gjs overrides

---

data/preset/escola.yaml

Don't need it and stuff isnt marked as
featured on portal anyway

Remove filter on escola

---

data/css/escola.scss
data/css/library_list.scss
data/preset/escola.yaml
data/preset/library-list.yaml
js/app/modules/banner/dynamic.js
js/app/modules/controller/mesh.js

https://phabricator.endlessm.com/T14133

Changes to escola template based on Design QA

---

js/app/widgets/dynamicLogo.js

https://phabricator.endlessm.com/T14128

T14128 (fix for logo widget min and max sizes)

---

ekncontent/ekncontent/eknc-video-object-model.c
js/app/interfaces/card.js
tests/js/app/interfaces/testCard.js

https://phabricator.endlessm.com/T14939

Duration field is stored in seconds, not milliseconds

---

data/css/library_list.scss

https://phabricator.endlessm.com/T14128

Use correct font on set page

---

js/app/application.js
js/search/domain.js
js/search/downloader.js
js/search/engine.js
js/search/utils.js

https://phabricator.endlessm.com/T14643

Fix content updates (eos3.1 branch only)

---

ekncontent/ekncontent/eknc-domain.c

https://phabricator.endlessm.com/T15065

T15065 (part 1)

---

Makefile.am
eos-knowledge.gresource.xml
js/app/interfaces/module.js
js/app/introspect.js
tests/js/app/interfaces/testModule.js
tools/introspect.in
tools/introspect.js

https://phabricator.endlessm.com/T15141

Module introspection

---

js/app/modules/contentGroup/contentGroup.js
tests/js/app/modules/contentGroup/testContentGroup.js

https://phabricator.endlessm.com/T15041

Error log fixes

---

lib/eosknowledgeprivate/ekn-media-bin.c

https://phabricator.endlessm.com/T15106

EknMediaBin: print FPS in gst info level

---

.gitignore

https://phabricator.endlessm.com/T15141

Fix .gitignore for introspect

---

data/preset/escola.yaml

Now backbutton appears on Escola apps
http://phabricator.endlessm.com/T15277

Add Layout.Navigation to escola.yaml

---

data/css/escola.scss

https://phabricator.endlessm.com/T15252

Make sure background stretches to fill width of set page

---

data/preset/library-list.yaml
js/app/widgets/infiniteScrolledWindow.js

https://phabricator.endlessm.com/T15802

Fix library-list with two levels of hierarchy

---

lib/eosknowledgeprivate/ekn-media-bin.c

Fixed video_widget and playbin object leaks.
https://phabricator.endlessm.com/T15393

EknMediaBin: fixed object leaks

---

debian/eos-knowledge-0-bin.install

https://phabricator.endlessm.com/T15141

Add introspect to eos-knowledge-0-bin package

---

tools/kermit.js

Fallout from ekncontent port.
https://phabricator.endlessm.com/T15997

kermit: Fix query

---

debian/control

https://phabricator.endlessm.com/T15785

Replace dependency on ruby-sass with sassc

---

data/css/course.scss
data/css/escola.scss
js/app/modules/banner/appMetadata.js
js/app/modules/contentGroup/dynamicTitle.js
js/app/modules/contentGroup/staticText.js
js/app/modules/decoration/separator.js

I grepped in eos-subscriptions-apps as well, and though these change the CSS names, nothing in eos-subscriptions-apps seemed to be using those CSS names.
https://phabricator.endlessm.com/T14833

More documentation adjustments

---

tools/picard.js

So that we reset Adwaita styling
https://phabricator.endlessm.com/T15903

Add base theme to picard as well

---

Makefile.am
data/css/_base.scss
data/css/modules/layout/_placeholder.scss
eos-knowledge.gresource.xml
js/app/modules/layout/placeholder.js
po/POTFILES.in

For use during development, to indicate a space where some module should
go that doesn't exist yet, or indicate some part of the YAML that hasn't
been filled in yet.
https://phabricator.endlessm.com/T16204

modules: Layout.Placeholder module

---

data/preset/news.yaml

Request from design.
https://phabricator.endlessm.com/T16345

news: Four categories on front page

---

debian/control

https://phabricator.endlessm.com/T15785

T15785 (fixes for debian/control)

---

data/css/encyclopedia.scss
data/preset/encyclopedia.yaml

https://phabricator.endlessm.com/T16259

Encyclopedia dynamic logo

---

Makefile.am
eos-knowledge.gresource.xml
js/app/modules/selection/staticArticles.js
tests/js/app/modules/selection/testStaticArticles.js

https://phabricator.endlessm.com/T16557

T16557 (new selection for static pages)

---

data/templates/article-wrapper.mst
js/app/application.js
js/app/articleHTMLRenderer.js
tests/js/app/testArticleHTMLRenderer.js

https://phabricator.endlessm.com/T16145

Custom web overrides CSS

---

docs/framework/hotdoc.json

https://phabricator.endlessm.com/T16851

docs: Add "edit on github" button

---

ekncontent/ekncontent/eknc-content-object-model.c
ekncontent/overrides/EosKnowledgeContent.js

https://phabricator.endlessm.com/T16620

ekncontent: Read "discoveryFeedContent" property on articles

---

data/preset/news.yaml
js/app/interfaces/articleContent.js
js/app/modules/card/knowledgeDocument.js
js/app/modules/card/video.js
lib/eosknowledgeprivate/EknMediaBin.ui
lib/eosknowledgeprivate/ekn-media-bin.c
lib/eosknowledgeprivate/ekn-media-bin.css
tests/compliance.js
tests/js/app/modules/card/testVideo.js

https://phabricator.endlessm.com/T16867

News Preset: added basic support for video articles

---

data/preset/buffet.yaml
ekncontent/ekncontent/eknc-query-object.c
ekncontent/tests/ekncontent/testQueryObject.js
js/app/modules/selection/articleContext.js
tests/js/app/interfaces/testModule.js
tests/js/app/modules/filter/testCurrentSet.js
tests/js/app/modules/selection/testArticlesForSetCrossSection.js
tests/minimal.js
tests/mockEngine.js

https://phabricator.endlessm.com/T13175

Minor fixes from T13175

---

Makefile.am
data/css/_base.scss
data/css/modules/arrangement/_sideBySide.scss
data/css/modules/navigation/_topMenu.scss
data/css/news.scss
data/preset/news.yaml
data/widgets/card/title.ui
js/app/modules/arrangement/sideBySide.js
js/app/modules/card/title.js
js/app/modules/navigation/topMenu.js
tests/js/app/modules/arrangement/testSideBySide.js

Added dropdown menu to show cards that do not fit in the allocated space.
The container will adapt automatically to the allocated size showing all the
cards possible and packend the rest in a dropdown menu.
https://phabricator.endlessm.com/T16646

Arrangement.SideBySide: made arrangement responsive.

---

js/app/widgets/imageCoverFrame.js

By Sam Spilsbury in
https://github.com/endlessm/eos-discovery-feed/pull/14.
https://phabricator.endlessm.com/T16865

ImageCoverFrame: Make pixbuf loading asynchronous

---

data/css/news.scss
data/preset/news.yaml

Replace nav-content selection with related module
https://phabricator.endlessm.com/T17303

News preset: use related articles selection

---

js/app/moduleFactory.js
js/app/modules/arrangement/tiledGrid.js
js/app/modules/layout/box.js
js/app/modules/pager/simple.js
js/app/utils.js
js/app/widgets/formattableLabel.js
tests/js/app/widgets/testSpaceContainer.js
tests/utils.js

https://phabricator.endlessm.com/T17220

Fix too many arguments warnings

---

data/css/buffet.scss
data/css/modules/card/_base.scss
data/css/modules/card/_deck.scss
js/app/modules/card/deck.js
js/app/modules/card/defaultFamily.js
js/app/modules/card/list.js
js/app/utils.js

Remove bottom right arrow from deck, defaultFamily and list cards
https://phabricator.endlessm.com/T17305

Cards: remove bottom right arrow

---

Makefile.am
data/css/_base.scss
data/css/blog.scss
data/css/buffet.scss
data/css/escola.scss
data/css/modules/card/_default.scss
data/css/news.scss
data/preset/blog.yaml
data/preset/buffet.yaml
data/preset/escola.yaml
data/preset/news.yaml
data/widgets/card/default.ui
eos-knowledge.gresource.xml
js/app/modules/card/default.js
tests/js/app/modules/card/testDefault.js

The "DefaultFamily" name was a misunderstanding between the engineering
team and the design team.
https://phabricator.endlessm.com/T17332

Rename Card.DefaultFamily to Card.Default

---

js/app/interfaces/module.js
js/app/modules/card/media.js
js/app/modules/contentGroup/mediaLightbox.js
js/app/widgets/previewer.js
tests/js/app/modules/card/testMedia.js
tests/js/app/widgets/testPreviewer.js

https://phabricator.endlessm.com/T16868

Card.Media: add support for videos objects

---

data/preset/news.yaml

https://phabricator.endlessm.com/T17380

News preset: remove branding page.

---

ekncontent/ekncontent/eknc-domain.c
ekncontent/ekncontent/eknc-xapian-bridge.c
ekncontent/ekncontent/eknc-xapian-bridge.h

The results of the probe aren't yet used.

Probe for features supported by xapian-bridge in use

---

js/app/modules/arrangement/sideBySide.js
tests/js/app/modules/arrangement/testSideBySide.js

https://phabricator.endlessm.com/T17424

testSideBySide.js adapted test case to new behavior.

---

ekncontent/docs/reference/ekncontent/Makefile.am
ekncontent/docs/reference/ekncontent/eos-knowledge-content-sections.txt
ekncontent/ekncontent/eknc-xapian-bridge.c

https://phabricator.endlessm.com/T17601

Fix documentation checks

---

ekncontent/ekncontent/eknc-query-object.c
ekncontent/ekncontent/eknc-xapian-bridge.c

The three-way `eknc_query_object_new_from_object()` call seems clumsy.  I wondered about just calling it without any extra properties (and tweaking `eknc_query_object_new_from_object()` so it can be called with just `(source, NULL)`), and then setting whichever properties apply.  However setting a property seems to require messing around with `GVariant` which seems like it's going to end up with even clumsier code.
Any better ideas?

Add corrected-query property

---

data/css/news.scss

https://phabricator.endlessm.com/T17559

News CSS: set font weight on dropdown menu cards

---

data/css/modules/card/_base.scss
data/images/play_icon.svg
data/widgets/card/default.ui
data/widgets/card/list.ui
eos-knowledge.gresource.xml
js/app/interfaces/card.js
js/app/modules/card/default.js
js/app/modules/card/list.js

Add method for implementator classes to support a media overlay for audio and video data models.
https://phabricator.endlessm.com/T16882

Card interface: add set_media_overlay_from_model() method

---

.gitignore

https://phabricator.endlessm.com/T17780

Adding tools/introspect-local to .gitignore

---

ekncontent/Makefile.am
ekncontent/docs/reference/ekncontent/eos-knowledge-content-docs.xml
ekncontent/docs/reference/ekncontent/eos-knowledge-content-sections.txt
ekncontent/ekncontent/eknc-dictionary-object-model.c
ekncontent/ekncontent/eknc-dictionary-object-model.h
ekncontent/ekncontent/eknc-object-model.c
ekncontent/overrides/EosKnowledgeContent.js
ekncontent/tests/ekncontent/testDictionaryObjectModel.js

This can be used by the WordOfTheDay app.
https://phabricator.endlessm.com/T17276

Add a DictionaryObjectModel

---

ekncontent/tests/ekncontent/testDictionaryObjectModel.js

'_' instead of '-' in property names, this fixes the build.

Test DictionaryObjectModel: correct usage of property

---

js/app/modules/navigation/topMenu.js
js/app/utils.js

https://phabricator.endlessm.com/T10722

Navigation.TopMenu: go to home page on banner click

---

tools/picard.js

Add a way to choose which type of dummy ObjectModel to use when creating cards
https://phabricator.endlessm.com/T17891

Picard: add card model type combo box

---

js/app/application.js

In the application's constructor, GTK has not yet been initialized.
https://phabricator.endlessm.com/T17897

application: Don't initialize icon theme too early

---

ekncontent/ekncontent/eknc-domain.c

https://phabricator.endlessm.com/T17999

EkncDomain: support multiple subscriptions

---

js/app/modules/card/knowledgeDocument.js
tests/js/app/modules/card/testKnowledgeDocument.js
tests/mockWidgets.js

https://phabricator.endlessm.com/T18071

T18071 (second approach)

---

Makefile.am
ekncontent/overrides/EosKnowledgeContent.js
js/app/modules/selection/xapian.js
tests/js/app/modules/selection/testXapian.js

https://phabricator.endlessm.com/T17143

Fix Xapian query regression in travel app

---

Makefile.am
data/css/gallery.scss
data/preset/gallery.yaml
eos-knowledge.gresource.xml
tools/ka-customizer

New template 'Gallery', and template CSS.
Added to Makefile, gresource, and Kactus
https://phabricator.endlessm.com/T17334

Creating gallery template and CSS

---

js/app/modules/arrangement/half.js
js/app/modules/arrangement/piano.js
js/app/modules/arrangement/quarter.js
js/app/modules/arrangement/quilt.js
js/app/modules/arrangement/squareGuys.js
js/app/modules/arrangement/thirdRock.js
js/app/modules/arrangement/thirties.js
js/app/modules/arrangement/windshield.js
js/app/modules/card/default.js
js/app/widgets/spaceContainer.js

https://phabricator.endlessm.com/T18286

Eliminate annoying warnings

---

about.md

Views are now distinguished from Cards.
https://phabricator.endlessm.com/T16467

about: Add View to module kind tree

---

eos-knowledge.gresource.xml
js/app/application.js
js/app/buffetHistoryStore.js
js/app/courseHistoryStore.js
js/app/entryPoints.js
js/app/historyStore.js
js/app/meshHistoryStore.js
js/app/utils.js
tests/js/app/testHistoryStore.js
tests/js/app/testMeshHistoryStore.js

This is working and ready for CR. See T18516 for details.

Add support for content access metrics

---

ekncontent/tests/ekncontent/testDomain.js
ekncontent/tests/ekncontent/testEngine.js

This should ensure that g_get_user_data_dir() always returns something
that exists, even in a clean Jenkins environment.
https://phabricator.endlessm.com/T18932

build: Use $TMPDIR for $XDG_DATA_HOME in tests

---

Makefile.am
tests/autobahn/basic.pot
tests/autobahn/test-autobahn-catalog

https://phabricator.endlessm.com/T18981

Fixes for running tests in flatpak sandbox

---

Makefile.am
ekncontent/ekncontent/eknc-content-object-model.c
ekncontent/ekncontent/eknc-domain.c
ekncontent/ekncontent/eknc-domain.h
ekncontent/ekncontent/eknc-engine.c
ekncontent/ekncontent/eknc-engine.h
ekncontent/ekncontent/eknc-utils.c
tests/js/app/modules/filter/testOtherGroup.js

Picked up with LSan and Valgrind.
https://phabricator.endlessm.com/T18981

ekncontent: Fix memory leaks

---

lib/eosknowledgeprivate/ekn-media-bin.c

This was causing use-after-free when switching from one video to another.
https://phabricator.endlessm.com/T19444

EknMediaBin: Remove revealer timeout on dispose

---

js/app/historyItem.js
js/app/historyStore.js
js/app/modules/window/simple.js
js/app/utils.js
tests/js/app/testHistoryItem.js
tests/js/app/testHistoryStore.js

https://phabricator.endlessm.com/T18524

Sharing metrics

---

data/preset/A.yaml

In order to be able to show thumbnails when they are present and good
enough quality.
https://phabricator.endlessm.com/T19550

preset A: Allow all Card.Default variants in set page

---

data/widgets/websharedialog.ui
eos-knowledge.gresource.xml
js/app/historyStore.js
js/app/modules/window/simple.js
js/app/widgets/webShareDialog.js

https://phabricator.endlessm.com/T19427

HistoryStore: implement facebook sharing with WebShareDialog

---

js/app/widgets/webShareDialog.js

Use DBus api to avoid having to add an extra dependecy to the SDK.
https://phabricator.endlessm.com/T19427

WebShareDialog: use DBus api instead of GOA bindings

---

Makefile.am
data/css/_base.scss
data/css/modules/contentGroup/_mediaLightbox.scss
data/css/widgets/_shareActionBox.scss
eos-knowledge.gresource.xml
js/app/historyItem.js
js/app/historyStore.js
js/app/modules/contentGroup/mediaLightbox.js
js/app/widgets/lightbox.js
js/app/widgets/shareActionBox.js

https://phabricator.endlessm.com/T18523

MediaLightBox: add share actions under close button

---

ekncontent/ekncontent/eknc-utils.c

This mitigates a memory corruption issue that causes critical errors to
be printed in the console when using JSON-GLib to convert JSON into
GVariant for array-based properties that GJS does not support.
The memory corruption is still there, and will present itself given
enough random application launches of some of the knowledge apps.
https://phabricator.endlessm.com/T19561

Manually parse some GVariant properties

---

js/app/modules/layout/dynamicBackground.js

Calling get_background_color() on a style context makes the context emit
the style-updated signal which was making the handler be called continuously.
https://phabricator.endlessm.com/T19667

Layout.DynamicBackground: break recursive style-updated signal emission

---

js/app/historyItem.js
js/app/historyStore.js
tests/js/app/testMeshHistoryStore.js

https://phabricator.endlessm.com/T19814

Handle opening videos from desktop search

---

ekncontent/ekncontent/eknc-utils.c

https://phabricator.endlessm.com/T19561

T19561 (part2)

---

ekncontent/ekncontent/eknc-domain.c
ekncontent/ekncontent/eknc-query-object.c

Backport of what was done on master, much smaller in scope.
https://phabricator.endlessm.com/T19825

Fix spelling correction

---

README.md
ekncontent/ekncontent/eknc-domain.c
ekncontent/ekncontent/eknc-engine.c
js/app/interfaces/order.js
tools/kermit.js

https://phabricator.endlessm.com/T19965

Remove all mention of xapian-bridge

---

ekncontent/docs/reference/ekncontent/eos-knowledge-content-sections.txt
ekncontent/ekncontent/eknc-database-manager.c
ekncontent/ekncontent/eknc-query-object.c
ekncontent/ekncontent/eknc-query-object.h
ekncontent/overrides/EosKnowledgeContent.js

This pull request is on top of #1565 and should be rebased after that one is merged.
https://phabricator.endlessm.com/T20449

Query logging

---

data/preset/blog.yaml
data/preset/news.yaml

https://phabricator.endlessm.com/T20371

Remove nav-content from news, blog and buffet presets

---

ekncontent/ekncontent/eknc-query-object.c

https://phabricator.endlessm.com/T20757

Suggestions from Olly

---

ekncontent/ekncontent/eknc-database-manager.c

Some time ago, Olly fixed the database building code to not produce
spelling dictionaries with newlines on the end of each word:
https://github.com/endlessm/endless-content-factory/pull/755
However, not all databases have been rebuilt since then. We need to
manually remove newlines from Xapian's corrected terms if they are still
present. Otherwise, a spurious 'title:\n' will get added to the query,
and that will not be recognized as a prefix and therefore always search
for articles with 'title' in the title.
https://phabricator.endlessm.com/T20730

ekncontent: Strip newlines from Xapian's corrected terms

---

ekncontent/configure.ac
ekncontent/ekncontent/eknc-article-object-model.c
ekncontent/ekncontent/eknc-audio-object-model.c
ekncontent/ekncontent/eknc-content-object-model.c
ekncontent/ekncontent/eknc-database-manager.c
ekncontent/ekncontent/eknc-dictionary-object-model.c
ekncontent/ekncontent/eknc-image-object-model.c
ekncontent/ekncontent/eknc-media-object-model.c
ekncontent/ekncontent/eknc-object-model.c
ekncontent/ekncontent/eknc-query-object.c
ekncontent/ekncontent/eknc-set-object-model.c
ekncontent/ekncontent/eknc-video-object-model.c
js/app/modules/contentGroup/contentGroup.js
js/app/modules/contentGroup/dynamicTitle.js

https://phabricator.endlessm.com/T20695

Add profiling probes to e-k-l

---

data/templates/css/wikihow.scss
data/templates/css/wikimedia.scss

https://phabricator.endlessm.com/T20355

Wikimedia & Wikihow: Fix article title size bug

---

tests/js/app/modules/navigation/testSearchBox.js
tests/js/app/modules/pager/testSimple.js
tests/mockWidgets.js

https://phabricator.endlessm.com/T20956

Test warning fixes

---

docs/framework/modules.md
docs/framework/modules/window.md
docs/framework/sitemap.txt
js/app/introspect.js
js/app/modules/window/simple.js

https://phabricator.endlessm.com/T11156

Refresh Window.Simple documentation

---

js/app/utils.js
js/app/widgets/webShareDialog.js
tests/js/app/testUtils.js

https://phabricator.endlessm.com/T21017

Legacy EKN IDs fix

---

docs/Makefile.am

https://phabricator.endlessm.com/T11156

T11156 (fix docs make dist)

---

js/app/articleHTMLRenderer.js
js/app/modules/navigation/searchBox.js

https://phabricator.endlessm.com/T21027

Fix warnings

---

contributing.md

instead of JHBuild.
https://phabricator.endlessm.com/T20376

Change build instructions to use Flapjack

---

data/widgets/websharedialog.ui
js/app/widgets/webShareDialog.js

Open control center if account AttentionNeeded is true
https://phabricator.endlessm.com/T20960

WebShareDialog: handle expired sessions

---

data/widgets/websharedialog.ui
js/app/widgets/webShareDialog.js
tests/js/app/testHistoryStore.js

Show error messages to users in the infobar.
https://phabricator.endlessm.com/T21193

WebShareDialog: handle webkit load-failed signal

---

po/POTFILES.in

https://phabricator.endlessm.com/T20960

T20960 (fix missing strings)

---

js/app/articleHTMLRenderer.js
tests/js/app/testArticleHTMLRenderer.js

https://phabricator.endlessm.com/T21271

T21271: Some more testing for articleHTMLRenderer

---

configure.ac
docs/Makefile.am
docs/framework/hotdoc.json
docs/framework/theme/templates/navbar_center.html

https://phabricator.endlessm.com/T21126

Endless Hotdoc theme

---

data/preset/blog.yaml
data/preset/buffet.yaml
data/preset/escola.yaml
data/preset/gallery.yaml
data/preset/news.yaml
js/app/modules/contentGroup/staticText.js
js/app/modules/layout/overlay.js

If you don't do this, the title is off-center in a weird way. You can
still customize these properties, but they should have good default
values.
https://phabricator.endlessm.com/T21365

ContentGroup.StaticText: expand and align by default

---

js/app/widgets/themeableImage.js

Implemet margin, border and padding CSS properly
Use contain background-size to prevent image cliping
https://phabricator.endlessm.com/T21569

ThemeableImage: fix regresions

---

js/app/utils.js

Use pointer hand instead of grab hand
https://phabricator.endlessm.com/T21802

Utils: use proper hand on set_hand_cursor_on_widget()

---

tests/js/app/modules/arrangement/testTiledGrid.js
tests/js/app/modules/banner/testContext.js
tests/js/app/modules/layout/testBrandPage.js
tests/js/app/modules/layout/testNavigation.js
tests/js/app/modules/navigation/testTopMenu.js
tests/js/app/modules/order/testPublishedDate.js
tests/js/app/modules/order/testSequence.js
tests/js/app/modules/pager/testParallaxBackground.js

Fix WebShareDialog missing resource warning
https://phabricator.endlessm.com/T21657

Register resource in all tests that needs them.

---

Makefile.am
tools/.pylintrc
tools/shard_doctor

This tool can be used to detect duplicate articles in the subscriptions of an app and show its metadata diffs
https://phabricator.endlessm.com/T21652 is the parent story but the PR is more orthogonal to its completion

Add shard_doctor to tooling

---

data/templates/article-wrapper.mst
eos-knowledge.gresource.xml

https://phabricator.endlessm.com/T22052

Revert article-wrapper.mst removal

---

data/css/library.scss
data/css/library_list.scss
data/widgets/layout/hamburgerBasement.ui
js/app/modules/contentGroup/contentGroup.js
js/app/modules/layout/hamburgerBasement.js
js/app/moltresEngine.js

https://phabricator.endlessm.com/T22044

Layout.HamburgerBasement improvements

---

Makefile.am
data/css/modules/navigation/_searchBox.scss
data/css/modules/window/_simple.scss
eos-knowledge.gresource.xml
js/app/modules/navigation/searchBox.js
js/app/widgets/searchBox.js
tests/js/app/widgets/testSearchBox.js

https://phabricator.endlessm.com/T20353

Move SearchBox to eos-knowledge-lib and partially improve theming

---

tests/js/app/testArticleHTMLRenderer.js

https://phabricator.endlessm.com/T22166

T22166: Fix failing articleHTMLRenderer tests

---

data/css/encyclopedia.scss
data/css/modules/navigation/_searchBox.scss
data/css/modules/window/_simple.scss
js/app/widgets/searchBox.js

https://phabricator.endlessm.com/T20353

More search bar visual fixes

---

docs/framework/tutorial/code/cc-ingester/index.js
docs/framework/tutorial/code/cc-ingester/package-lock.json
docs/framework/tutorial/code/cc-ingester/package.json
docs/framework/tutorial/code/cc-ingester2/index.js
docs/framework/tutorial/code/cc-ingester2/package-lock.json
docs/framework/tutorial/code/cc-ingester2/package.json
docs/framework/tutorial/ingester.md
docs/framework/tutorial/shard.md

https://phabricator.endlessm.com/T21578

More tutorial changes

---

js/app/widgets/searchBox.js

s/Gtk.EVENT_PROPAGATE/Gdk.EVENT_PROPAGATE
https://phabricator.endlessm.com/T22388

EknSearchBox: fix typo

---

js/app/modules/card/default.js

https://phabricator.endlessm.com/T22379

T22379 (fix)

---

data/css/modules/navigation/_searchBox.scss

Some extra changes to make the search box look less crowded when it is
inside the title bar.
https://phabricator.endlessm.com/T22634

Navigation.SearchBox: Adjust style in title bar

---

docs/framework/tutorial/code/app/org.example.CreativeCommonsBlog.json

https://phabricator.endlessm.com/T22633

Restore tutorial example

---

docs/framework/tutorial/code/app/org.example.CreativeCommonsBlog.json

https://phabricator.endlessm.com/T22633

Restore example file to original state

---

docs/framework/concepts/custom_modules.md

https://phabricator.endlessm.com/T22910

T22910 (fix docs)

---

tests/js/framework/testArticleHTMLRenderer.js

https://phabricator.endlessm.com/T23017

tests: Remove tests moved to eos-knowledge-content-renderer

---

docs/framework/tutorial/code/cc-ingester/index.js
docs/framework/tutorial/code/cc-ingester/package-lock.json
docs/framework/tutorial/code/cc-ingester/package.json
docs/framework/tutorial/code/cc-ingester2/index.js
docs/framework/tutorial/code/cc-ingester2/package-lock.json
docs/framework/tutorial/code/cc-ingester2/package.json
docs/framework/tutorial/ingester.md

- Leave the previous code to show what kind of code the utility saves
to write.
- Bump libingester dependency in the two ingesters.
https://phabricator.endlessm.com/T23005

docs: Improve ingesters in tutorial with cleanup utility

---

js/framework/widgets/PDFView.js

The icon view redraws itself everytime the list store changes which makes
updating thumbnails one by one really slow.
To speed up things we only update once when we have 16 thumbs and when we finished
generating all of them.
https://phabricator.endlessm.com/T22974

PDFView: improve thumbnail generation performance

---

data/css/widgets/_pDFView.scss

Otherwise both TOC and  Content sliders get
too small, to the point is hard to spot and
to use.
https://phabricator.endlessm.com/T23215

PDFView: Don't let slider get too small

---

Makefile.am
tools/shard_stats

https://phabricator.endlessm.com/T23256

T23256 (shard_stats)

---

js/framework/application.js

This is necessary for supplying extra custom modules for Endless Hack.
https://phabricator.endlessm.com/T23678

application: Allow extra GResource files with -E

---

js/framework/widgets/dynamicLogo.js

https://phabricator.endlessm.com/T23415

dynamicLogo: Fix logo height to text height

---

js/framework/widgets/dynamicLogo.js

This recolors the logo SVG to match the text color given to the
.BannerDynamic__logo widget in Banner.Dynamic.
https://phabricator.endlessm.com/T23839

Banner.Dynamic: Allow coloring the logo SVG

---

tools/autobahn

https://phabricator.endlessm.com/T24296

autobahn: Allow more than one include path

---

releases/sdk5.md

https://phabricator.endlessm.com/T27321

Add release notes for SDK version 5.5

---

js/framework/historyStore.js
js/framework/modules/contentGroup/mediaLightbox.js
js/framework/modules/view/media.js

The idea here is to allow to open audio and video files by opening links to those, without the complexity of adding those files as children of the original article.
https://phabricator.endlessm.com/T28066

T28066 corenav

---

js/framework/modules/window/simple.js
js/framework/widgets/searchBox.js
tools/picard.js

This updates eos-knowledge-lib to support changes in endlessm/eos-sdk#4187.
https://phabricator.endlessm.com/T21463

Update widgets to work with regular titlebars (T21463)

---

js/framework/articleHTMLRenderer.js
js/framework/modules/view/document.js
js/framework/utils.js
js/framework/widgets/eknWebview.js

This depends on https://github.com/endlessm/libdmodel/pull/14
I made this originally for the `sdk-5` branch because I wasn't able to build my SDK with Flapjack against SDK-6, I have to ask @dylanmccall how to do that...
The point is that the port to SDK-6 was untested, so this code is untested. Gonna put it on Draft mode until I figure out how to test it.
https://phabricator.endlessm.com/T29258

T29258 kolibri html5 zip

---

lib/eosknowledgeprivate/ekn-media-bin.c

Previously, this function used the output of glGetString to decide
whether to use gtkglsink, but the version of gtkglsink included in the
SDK also supports EGL contexts.
https://phabricator.endlessm.com/T29524

Support EGL contexts in ekn_media_bin_gl_check

---

data/templates/article-wrapper.mst
js/framework/application.js
js/framework/articleHTMLRenderer.js
js/framework/modules/contentGroup/mediaLightbox.js
js/framework/modules/view/document.js
js/framework/widgets/eknWebview.js
lib/web-extensions/gresourceplugin.c
lib/web-extensions/scrollplugin.c
lib/web-extensions/tooltipplugin.c
tests/js/framework/interfaces/testModule.js
tests/js/framework/modules/arrangement/testSideBySide.js
tests/js/framework/modules/arrangement/testThirdRock.js
tests/js/framework/modules/contentGroup/testMediaLightbox.js
tests/js/framework/modules/view/testDocument.js
tests/js/framework/testArticleHTMLRenderer.js
tests/mockWidgets.js

This PR make some adaptations to eos-knowledge-lib to support ZIM files and add support for custom client side CSS and JS files.
https://phabricator.endlessm.com/T26276

T26276 libzim libdmodel

---

js/framework/modules/layout/articleStack.js

https://phabricator.endlessm.com/T30655

T30655 fix references tooltips

---

releases/sdk6.md

https://phabricator.endlessm.com/T30668

Add release notes for SDK version 6.2

---

docs.md
releases/schedule.md

Spotted while looking at
https://phabricator.endlessm.com/T30668

Add links to SDK 6 docs & release schedule

---

releases/sdk5.md

https://phabricator.endlessm.com/T27285

Release notes for 5.7 and 5.8

---

releases/sdk6.md

https://phabricator.endlessm.com/T31275

Add release notes for SDK version 6.3
